services:
  database:
    image: "mysql:9.4-oraclelinux9"
    container_name: zenon_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-test@123}
      - MYSQL_DATABASE=${DB_NAME:-zenon_db}
    ports:
      - "3306:3306"
    volumes:
      - db-zenon:/var/lib/mysql


volumes:
  db-zenon: